// 公開ページの「管理画面から編集できる文言・画像」の定義（中央レジストリ）。
// - key: ページ内での識別子（Sanityの pageContent ドキュメントの上書きキーと対応）
// - label: 管理画面に表示する項目名
// - type: text(1行) / textarea(複数行) / image(画像)
// - default: 現在のハードコード文言（上書きが保存されていない場合はこの値で表示される）
//
// ここに定義されたページ・フィールドだけが /admin/pages の編集対象になる。
// 公開ページ側は usePageContent() でこのデフォルトとSanityの上書き値をマージして表示する。
// 改行(\n)を含むデフォルトは whitespace-pre-line で表示される前提。

export interface ContentField {
  key: string;
  label: string;
  type: 'text' | 'textarea' | 'image';
  default: string;
}

export interface PageDefinition {
  title: string;
  path: string;
  fields: ContentField[];
}

export const pageContentRegistry: Record<string, PageDefinition> = {
  home: {
    title: 'トップページ',
    path: '/',
    fields: [
      { key: 'aboutTitle', label: 'Aboutセクション 見出し', type: 'text', default: '小さな自然、大きな癒し' },
      { key: 'aboutLead', label: 'Aboutセクション リード文', type: 'textarea', default: '北海道初の苔テラリウム専門店として、一つひとつ手作業で作り上げる本格的なテラリウムをお届けします。' },
      { key: 'aboutSub', label: 'Aboutセクション サブ文', type: 'textarea', default: '忙しい日常の中で、ふと目に入る小さな緑の世界が、あなたの心に安らぎをもたらします。' },
      { key: 'card1Title', label: '価値カード1 タイトル', type: 'text', default: '職人の技' },
      { key: 'card1Desc', label: '価値カード1 説明', type: 'textarea', default: '一つひとつ手作業で丁寧に作られた本物のテラリウム' },
      { key: 'card2Title', label: '価値カード2 タイトル', type: 'text', default: '北海道初' },
      { key: 'card2Desc', label: '価値カード2 説明', type: 'textarea', default: '苔テラリウムの専門店として地域密着' },
      { key: 'card3Title', label: '価値カード3 タイトル', type: 'text', default: '学べる' },
      { key: 'card3Desc', label: '価値カード3 説明', type: 'textarea', default: '初心者から上級者まで楽しめるワークショップ' },
      { key: 'carousel1Title', label: '作品カルーセル1 タイトル', type: 'text', default: 'テラリウム作品' },
      { key: 'carousel1Desc', label: '作品カルーセル1 説明', type: 'textarea', default: '苔が織りなす穏やかな景色。日常の中に小さな癒しをお届けします。' },
      { key: 'carousel1Image', label: '作品カルーセル1 画像', type: 'image', default: '/images/products/moss-country_products_glass.png' },
      { key: 'carousel2Title', label: '作品カルーセル2 タイトル', type: 'text', default: '苔玉・苔盆栽' },
      { key: 'carousel2Desc', label: '作品カルーセル2 説明', type: 'textarea', default: '日本の伝統美と現代のライフスタイルを融合。和洋問わずどんな空間にも。' },
      { key: 'carousel2Image', label: '作品カルーセル2 画像', type: 'image', default: '/images/products/moss-country_products_mossball.png' },
      { key: 'carousel3Title', label: '作品カルーセル3 タイトル', type: 'text', default: '用品販売' },
      { key: 'carousel3Desc', label: '作品カルーセル3 説明', type: 'textarea', default: 'テラリウムづくりに使える道具や素材を揃えています。初心者の方でも安心して苔の世界を楽しめます。' },
      { key: 'carousel3Image', label: '作品カルーセル3 画像', type: 'image', default: '/images/products/care-guide.jpg' },
      { key: 'carousel4Title', label: '作品カルーセル4 タイトル', type: 'text', default: 'ワークショップ' },
      { key: 'carousel4Desc', label: '作品カルーセル4 説明', type: 'textarea', default: '職人による本格指導で自分だけのオリジナル作品を。初心者も安心の充実サポート。' },
      { key: 'carousel4Image', label: '作品カルーセル4 画像', type: 'image', default: '/images/workshop/mosscountry_workshop_blight.png' },
      { key: 'workshopTitle', label: 'ワークショップ案内 見出し', type: 'text', default: '自分の手で作る' },
      { key: 'workshopTitleAccent', label: 'ワークショップ案内 見出し強調部', type: 'text', default: '特別なテラリウム体験' },
      { key: 'workshopLead', label: 'ワークショップ案内 リード文', type: 'textarea', default: '経験豊富な職人が丁寧に指導する、本格的なテラリウム制作体験。初心者の方でも安心して参加できるよう、基礎から応用まで幅広いコースをご用意しています。' },
      { key: 'workshopPoint1', label: 'ワークショップ特徴1', type: 'text', default: '初心者から上級者まで対応' },
      { key: 'workshopPoint2', label: 'ワークショップ特徴2', type: 'text', default: '必要な材料・道具はすべて込み' },
      { key: 'workshopPoint3', label: 'ワークショップ特徴3', type: 'text', default: '作品はそのままお持ち帰り' },
      { key: 'workshopPoint4', label: 'ワークショップ特徴4', type: 'text', default: 'アフターフォロー完備' },
      { key: 'workshopImage', label: 'ワークショップ案内 画像', type: 'image', default: '/images/misc/moss03.jpeg' },
      { key: 'ctaTitle', label: 'CTAセクション 見出し', type: 'text', default: '今すぐテラリウムを始めませんか？' },
      { key: 'ctaLead', label: 'CTAセクション リード文', type: 'textarea', default: 'オンラインストアでは、厳選されたテラリウムを豊富に取り揃えています。全国配送対応で、あなたのもとへ小さな自然をお届けします。' },
      { key: 'sceneAboutImage', label: 'シーン背景 About（PC・横長16:9）', type: 'image', default: '/images/terrarium-generated/terrarium-artwork-woodland-arch-v1.png' },
      { key: 'sceneAboutImageMobile', label: 'シーン背景 About（スマホ・縦長9:16）', type: 'image', default: '/images/terrarium-generated/terrarium-mobile-artwork-root-cave-v1.png' },
      { key: 'sceneNewsImage', label: 'シーン背景 News（PC・横長16:9）', type: 'image', default: '/images/terrarium-generated/terrarium-artwork-moonlit-wetland-v1.png' },
      { key: 'sceneNewsImageMobile', label: 'シーン背景 News（スマホ・縦長9:16）', type: 'image', default: '/images/terrarium-generated/terrarium-mobile-artwork-misty-spires-v1.png' },
      { key: 'sceneProductsImage', label: 'シーン背景 Products（PC・横長16:9）', type: 'image', default: '/images/terrarium-generated/terrarium-hero-key-030-v1.png' },
      { key: 'sceneProductsImageMobile', label: 'シーン背景 Products（スマホ・縦長9:16）', type: 'image', default: '/images/terrarium-generated/terrarium-mobile-artwork-circular-spring-v1.png' },
      { key: 'sceneWorkshopImage', label: 'シーン背景 Workshop（PC・横長16:9）', type: 'image', default: '/images/terrarium-generated/terrarium-hero-angle-right-close-v1.png' },
      { key: 'sceneWorkshopImageMobile', label: 'シーン背景 Workshop（スマホ・縦長9:16）', type: 'image', default: '/images/terrarium-generated/terrarium-mobile-artwork-copper-fern-v1.png' },
      { key: 'sceneCtaImage', label: 'シーン背景 CTA（PC・横長16:9）', type: 'image', default: '/images/terrarium-generated/terrarium-artwork-basalt-ravine-v1.png' },
      { key: 'sceneCtaImageMobile', label: 'シーン背景 CTA（スマホ・縦長9:16）', type: 'image', default: '/images/terrarium-generated/terrarium-mobile-artwork-waterfall-cliff-v1.png' },
    ],
  },
  story: {
    title: 'ストーリーページ',
    path: '/story',
    fields: [
      { key: 'heroTitle', label: 'ヒーロー見出し', type: 'text', default: '小さな緑に込めた、大きな想い' },
      { key: 'heroLead', label: 'ヒーロー リード文', type: 'textarea', default: 'MOSS COUNTRYの想い、職人の技術、テラリウムへの情熱。私たちがなぜテラリウムを作り続けるのか、その理由をお話しします。' },
      { key: 'missionQuote', label: 'ミッション 引用文', type: 'textarea', default: '苔のある生活をあなたに。\n生活に癒しと和みを。' },
      { key: 'missionSub', label: 'ミッション 補足文', type: 'textarea', default: '苔の美しさを通して、心と暮らしに穏やかな時間を届けます。\n代表 立桶が提案する、新しい癒しのかたち。' },
      { key: 'value1Title', label: '価値観1 タイトル', type: 'text', default: 'AUTHENTICITY' },
      { key: 'value1Desc', label: '価値観1 説明', type: 'textarea', default: '苔の素晴らしさを伝えるために本物の美しさを追求しています。' },
      { key: 'value2Title', label: '価値観2 タイトル', type: 'text', default: 'CRAFTSMANSHIP' },
      { key: 'value2Desc', label: '価値観2 説明', type: 'textarea', default: '一つひとつ手作りで仕上げる、妥協なき職人技術。' },
      { key: 'value3Title', label: '価値観3 タイトル', type: 'text', default: 'SUSTAINABILITY' },
      { key: 'value3Desc', label: '価値観3 説明', type: 'textarea', default: '自然への敬意を込めた、持続可能な素材選びと製法。' },
      { key: 'value4Title', label: '価値観4 タイトル', type: 'text', default: 'EXPERIENCE' },
      { key: 'value4Desc', label: '価値観4 説明', type: 'textarea', default: '単なる商品ではなく、心に残る特別な体験を提供。' },
      { key: 'timeline1Title', label: '沿革1 タイトル', type: 'text', default: '自然との出会い' },
      { key: 'timeline1Desc', label: '沿革1 説明（HTML可、<br/>で改行）', type: 'textarea', default: '幼い頃から自然や動物が大好きで、両親に連れられて森や山へ出かけていました。中でも心を惹かれたのが、静かに息づく小さな苔。見つめているだけで心が落ち着き、時がたつのを忘れるほどでした。' },
      { key: 'timeline2Title', label: '沿革2 タイトル', type: 'text', default: '苔とテラリウムとの再会' },
      { key: 'timeline2Desc', label: '沿革2 説明（HTML可、<br/>で改行）', type: 'textarea', default: '自分の仕事を持ちたいと考えたとき、心に浮かんだのは苔でした。<br/>人々が知らない苔の魅力を伝え、癒しを届けたい。<br/>北海道には苔テラリウムの文化がまだ少なく、「それなら自分が広めよう」と決意しました。' },
      { key: 'timeline3Title', label: '沿革3 タイトル', type: 'text', default: 'MOSS COUNTRY設立' },
      { key: 'timeline3Desc', label: '沿革3 説明（HTML可、<br/>で改行）', type: 'textarea', default: '見本のない中、独学で知識を深め、店舗の掃除や改装も自らの手で。<br/>こうして札幌に苔の専門店「Moss Country」が誕生しました。<br/>名前には、「日本を苔の国=Moss Countryにしたい」という願いを込めています。' },
      { key: 'timeline4Title', label: '沿革4 タイトル', type: 'text', default: '未来へ' },
      { key: 'timeline4Desc', label: '沿革4 説明（HTML可、<br/>で改行）', type: 'textarea', default: 'これからはレンタル事業や苔セラピーを通じて、癒しの空間を広げていきます。<br/>子どもたちや地域の人々にも、苔を通して自然の素晴らしさを伝えたい。' },
      { key: 'craftsmanshipLead', label: '職人のこだわり リード文', type: 'textarea', default: 'ひとつひとつ丁寧に仕上げる手仕事。機械では表現できない繊細さと、苔への愛情が込められた唯一無二の作品です。自然と調和するように、手のぬくもりを大切にしています。' },
      { key: 'craftsmanshipImage', label: '職人のこだわり 画像', type: 'image', default: '/images/story/mosscountry_story_craftmanship.jpg' },
      { key: 'futureVisionTitle', label: '将来ビジョン 見出し', type: 'text', default: '札幌から広がる、苔の癒しの輪' },
      { key: 'futureVisionLead', label: '将来ビジョン リード文', type: 'textarea', default: 'Moss Countryは札幌を拠点に、まずは北海道各地へ、そしていずれは全国へと苔の癒しを届けていきます。苔の美しさや魅力を通じて、心にやすらぎと自然への優しさを育む文化を広げていきたいと考えています。' },
      { key: 'futureVisionImage', label: '将来ビジョン 画像', type: 'image', default: '/images/story/mosscountry_logo_sign.png' },
      { key: 'ctaTitle', label: 'CTAセクション 見出し', type: 'text', default: 'あなたも、この特別な世界へ' },
      { key: 'ctaLead', label: 'CTAセクション リード文', type: 'textarea', default: '立桶が創り出す、北海道発のテラリウム体験。あなたの日常に、新しい癒しをお届けします。' },
    ],
  },
  store: {
    title: '店舗情報ページ',
    path: '/store',
    fields: [
      { key: 'heroTitle', label: 'ヒーロー見出し', type: 'text', default: '北海道で出会う、本物のテラリウム体験' },
      { key: 'heroLead', label: 'ヒーロー リード文', type: 'textarea', default: '札幌の中心部にある私たちの店舗で、実際に手に取って、テラリウムの美しさと職人の技術を感じてください。' },
      { key: 'facility1Name', label: '設備1 名称', type: 'text', default: 'ショールーム' },
      { key: 'facility1Desc', label: '設備1 説明', type: 'textarea', default: '様々なサイズ・デザインのテラリウムを実際に手に取ってご覧いただけます' },
      { key: 'facility1Image', label: '設備1 画像', type: 'image', default: '/images/store/moss-country_store_items.png' },
      { key: 'facility2Name', label: '設備2 名称', type: 'text', default: 'ワークショップスペース' },
      { key: 'facility2Desc', label: '設備2 説明', type: 'textarea', default: '少人数制で丁寧に指導する、アットホームな制作スペース' },
      { key: 'facility2Image', label: '設備2 画像', type: 'image', default: '/images/store/moss-country_store_workshopspace.png' },
      { key: 'service1Title', label: 'サービス1 タイトル', type: 'text', default: '商品販売' },
      { key: 'service1Desc', label: 'サービス1 説明', type: 'text', default: '完成品テラリウムの販売' },
      { key: 'service1Price', label: 'サービス1 価格表示', type: 'text', default: '¥1000〜' },
      { key: 'service2Title', label: 'サービス2 タイトル', type: 'text', default: 'オーダーメイド' },
      { key: 'service2Desc', label: 'サービス2 説明', type: 'text', default: 'お客様のご要望に合わせた特別制作' },
      { key: 'service2Price', label: 'サービス2 価格表示', type: 'text', default: '¥5,000〜' },
      { key: 'service3Title', label: 'サービス3 タイトル', type: 'text', default: 'メンテナンス' },
      { key: 'service3Desc', label: 'サービス3 説明', type: 'text', default: 'テラリウムのお手入れ・修理' },
      { key: 'service3Price', label: 'サービス3 価格表示', type: 'text', default: '¥1,500〜' },
      { key: 'service4Title', label: 'サービス4 タイトル', type: 'text', default: 'ワークショップ' },
      { key: 'service4Desc', label: 'サービス4 説明', type: 'text', default: '手作り体験教室' },
      { key: 'service4Price', label: 'サービス4 価格表示', type: 'text', default: '¥2,500〜' },
      { key: 'galleryImage', label: '店舗の様子 画像', type: 'image', default: '/images/store/moss-country_store_appearance.png' },
      { key: 'ctaTitle', label: 'CTAセクション 見出し', type: 'text', default: 'ぜひ店舗にお越しください' },
      { key: 'ctaLead', label: 'CTAセクション リード文', type: 'textarea', default: '実際にテラリウムを手に取って、その美しさと職人の技術を感じてください。スタッフ一同、心よりお待ちしております。' },
    ],
  },
  contact: {
    title: 'お問い合わせページ',
    path: '/contact',
    fields: [
      { key: 'heroTitle', label: 'ヒーロー見出し', type: 'text', default: 'お問い合わせ' },
      { key: 'heroLead', label: 'ヒーロー リード文', type: 'textarea', default: 'テラリウムに関するご質問、ワークショップのお申し込み、オーダーメイドのご相談など、お気軽にお問い合わせください。' },
      { key: 'method1Title', label: '連絡方法1 タイトル', type: 'text', default: '電話でのお問い合わせ' },
      { key: 'method1Desc', label: '連絡方法1 説明', type: 'text', default: 'お急ぎの方はお電話でお気軽にお問い合わせください' },
      { key: 'method1Info', label: '連絡方法1 電話番号', type: 'text', default: '080-3605-6340' },
      { key: 'method1Hours', label: '連絡方法1 補足', type: 'text', default: '営業時間: 11:00-20:00 / 不定休（カレンダーをご確認ください）' },
      { key: 'method2Title', label: '連絡方法2 タイトル', type: 'text', default: 'メールでのお問い合わせ' },
      { key: 'method2Desc', label: '連絡方法2 説明', type: 'text', default: '詳しいご相談やお見積りはメールでも承ります' },
      { key: 'method2Info', label: '連絡方法2 メールアドレス', type: 'text', default: 'moss.country.kokenokuni@gmail.com' },
      { key: 'method2Hours', label: '連絡方法2 補足', type: 'text', default: '通常3営業日以内にご返信いたします' },
      { key: 'method3Title', label: '連絡方法3 タイトル', type: 'text', default: '店舗でのご相談' },
      { key: 'method3Desc', label: '連絡方法3 説明', type: 'text', default: '実際に商品を見ながらご相談いただけます' },
      { key: 'method3Info', label: '連絡方法3 住所', type: 'text', default: '札幌市西区発寒11条4丁目3-1' },
      { key: 'method3Hours', label: '連絡方法3 補足', type: 'text', default: '予約優先（当日来店も歓迎）' },
      { key: 'faq1Q', label: 'FAQ1 質問', type: 'text', default: 'ワークショップの予約はいつまでにすればよいですか？' },
      { key: 'faq1A', label: 'FAQ1 回答', type: 'textarea', default: '開催日の3日前までにご予約をお願いいたします。人気のコースは早めに満席になることがありますので、お早めのご予約をお勧めします。' },
      { key: 'faq2Q', label: 'FAQ2 質問', type: 'text', default: 'オーダーメイドの制作期間はどのくらいですか？' },
      { key: 'faq2A', label: 'FAQ2 回答', type: 'textarea', default: '内容により異なりますが、通常1-2週間程度お時間をいただいております。お急ぎの場合はご相談ください。' },
      { key: 'faq3Q', label: 'FAQ3 質問', type: 'text', default: 'テラリウムの配送は可能ですか？' },
      { key: 'faq3A', label: 'FAQ3 回答', type: 'textarea', default: 'はい、全国配送承っております。配送中の破損を防ぐため、特別な梱包でお送りいたします。送料は商品代金と別途頂戴いたします。' },
      { key: 'faq4Q', label: 'FAQ4 質問', type: 'text', default: 'メンテナンスサービスはありますか？' },
      { key: 'faq4A', label: 'FAQ4 回答', type: 'textarea', default: 'ご購入いただいたテラリウムのメンテナンスを承っております。植物の植え替えや容器のクリーニングなど、お気軽にご相談ください。' },
    ],
  },
  products: {
    title: '商品ページ',
    path: '/shop',
    fields: [
      { key: 'heroTitle', label: 'ヒーロー見出し（<br/>で改行）', type: 'text', default: 'MOSS COUNTRYの<br />テラリウムコレクション' },
      { key: 'heroLead', label: 'ヒーロー リード文', type: 'textarea', default: '一つひとつ手作業で丁寧に作られた本格テラリウム。初心者向けからプレミアムまで、あなたにぴったりの作品を見つけてください。' },
      { key: 'terrarium1Name', label: 'テラリウム区分1 名称', type: 'text', default: 'Mini Terrarium（ミニ・テラリウム）' },
      { key: 'terrarium1Desc', label: 'テラリウム区分1 説明', type: 'textarea', default: '小さなガラスの中に広がる、あなただけの癒しの森。手のひらの中で、穏やかな時間が流れます。' },
      { key: 'terrarium1Image', label: 'テラリウム区分1 画像', type: 'image', default: '/images/products/moss-country_products_bottle.png' },
      { key: 'terrarium2Name', label: 'テラリウム区分2 名称', type: 'text', default: 'Standard Terrarium（スタンダード・テラリウム）' },
      { key: 'terrarium2Desc', label: 'テラリウム区分2 説明', type: 'textarea', default: '日々の暮らしに寄り添う、やさしい苔の景色。静かな緑が、心に安らぎを届けます。' },
      { key: 'terrarium2Image', label: 'テラリウム区分2 画像', type: 'image', default: '/images/products/moss-country_products_glass.png' },
      { key: 'terrarium3Name', label: 'テラリウム区分3 名称', type: 'text', default: 'Grand Terrarium（グランド・テラリウム）' },
      { key: 'terrarium3Desc', label: 'テラリウム区分3 説明', type: 'textarea', default: '存在感ある苔の世界が、空間を豊かに彩ります。深みのある緑が、上質な癒しをもたらします。' },
      { key: 'terrarium3Image', label: 'テラリウム区分3 画像', type: 'image', default: '/images/products/moss-country_products_mossball.png' },
      { key: 'terrarium4Name', label: 'テラリウム区分4 名称', type: 'text', default: 'Premium Terrarium（プレミアム・テラリウム）' },
      { key: 'terrarium4Desc', label: 'テラリウム区分4 説明', type: 'textarea', default: '時を忘れるほどに美しい、静寂の世界。苔の深みが、空間をやさしく包み込みます。' },
      { key: 'terrarium4Image', label: 'テラリウム区分4 画像', type: 'image', default: '/images/products/moss-country_products_big.png' },
      { key: 'supply1Name', label: '関連用品1 名称', type: 'text', default: 'ツール' },
      { key: 'supply1Desc', label: '関連用品1 説明', type: 'text', default: 'テラリウム作りに必要な専門道具' },
      { key: 'supply1Image', label: '関連用品1 画像', type: 'image', default: '/images/products/terrarium-starter.jpg' },
      { key: 'supply2Name', label: '関連用品2 名称', type: 'text', default: '容器' },
      { key: 'supply2Desc', label: '関連用品2 説明', type: 'text', default: '様々なサイズとデザインのガラス容器' },
      { key: 'supply2Image', label: '関連用品2 画像', type: 'image', default: '/images/products/terrarium-standard.jpg' },
      { key: 'supply3Name', label: '関連用品3 名称', type: 'text', default: '素材' },
      { key: 'supply3Desc', label: '関連用品3 説明', type: 'text', default: '苔、土、石などの自然素材' },
      { key: 'supply3Image', label: '関連用品3 画像', type: 'image', default: '/images/products/terrarium-premium.jpg' },
      { key: 'supply4Name', label: '関連用品4 名称', type: 'text', default: 'フィギュア' },
      { key: 'supply4Desc', label: '関連用品4 説明', type: 'text', default: 'テラリウムを彩る小さな装飾品' },
      { key: 'supply4Image', label: '関連用品4 画像', type: 'image', default: '/images/products/terrarium-custom.jpg' },
      { key: 'care1Title', label: 'ケアガイド1 タイトル', type: 'text', default: '置き場所と光' },
      { key: 'care1Lead', label: 'ケアガイド1 説明', type: 'textarea', default: '直射日光は避け、ライトの光またはレース越しの光に当てましょう' },
      { key: 'care2Title', label: 'ケアガイド2 タイトル', type: 'text', default: '水やり' },
      { key: 'care2Lead', label: 'ケアガイド2 説明', type: 'textarea', default: '基本用土には、月に一度しっかりと水を与え、普段は週に一度ほど、苔と土の表面を軽く霧吹きで湿らせるだけでOK' },
      { key: 'care3Title', label: 'ケアガイド3 タイトル', type: 'text', default: '空気の入れ替え' },
      { key: 'care3Lead', label: 'ケアガイド3 説明', type: 'textarea', default: '余裕のある時は換気を行いましょう' },
      { key: 'care4Title', label: 'ケアガイド4 タイトル', type: 'text', default: '肥料' },
      { key: 'care4Lead', label: 'ケアガイド4 説明', type: 'textarea', default: '基本的には苔に肥料は使いません' },
      { key: 'care5Title', label: 'ケアガイド5 タイトル', type: 'text', default: 'お手入れ' },
      { key: 'care5Lead', label: 'ケアガイド5 説明', type: 'textarea', default: '適度にお手入れして見た目もきれいで清潔に保ちましょう' },
      { key: 'care6Title', label: 'ケアガイド6 タイトル', type: 'text', default: '移植' },
      { key: 'care6Lead', label: 'ケアガイド6 説明', type: 'textarea', default: '苔は移植先でも成長しやすいため、容器の交換なども行えます' },
      { key: 'ctaTitle', label: 'CTAセクション 見出し', type: 'text', default: 'あなたにぴったりのテラリウムを見つけませんか？' },
      { key: 'ctaLead', label: 'CTAセクション リード文', type: 'textarea', default: 'どの商品があなたに合うかわからない場合は、お気軽にお問い合わせください。専門スタッフがあなたのライフスタイルに合った最適なテラリウムをご提案します。' },
    ],
  },
  mobileWorkshop: {
    title: '出張ワークショップページ',
    path: '/workshop/mobile',
    fields: [
      { key: 'heroTitle', label: 'ヒーロー 見出し', type: 'text', default: '出張ワークショップ' },
      { key: 'heroImage', label: 'ヒーロー 画像', type: 'image', default: '/images/hero/workshop-hero.jpg' },
      { key: 'heroLead1', label: 'ヒーロー リード文1', type: 'textarea', default: 'あなたのイベント会場に、苔テラリウムの体験をお届けします。' },
      { key: 'heroLead2', label: 'ヒーロー リード文2', type: 'textarea', default: 'マルシェやフェスティバル、企業イベント、学校行事など、\nさまざまな場所で本格的なテラリウム制作を体験いただけます。' },
      { key: 'aboutTitle', label: 'サービス紹介 見出し', type: 'text', default: '出張ワークショップとは' },
      { key: 'aboutImage', label: 'サービス紹介 画像', type: 'image', default: '/images/workshop/mosscountry_workshop.png' },
      { key: 'aboutText1', label: 'サービス紹介 本文1', type: 'textarea', default: 'Moss Countryの出張ワークショップは、イベント会場やご指定の場所に職人が直接お伺いし、苔テラリウムの制作体験を提供するサービスです。' },
      { key: 'aboutText2', label: 'サービス紹介 本文2', type: 'textarea', default: '材料や道具はすべて持参するため、会場側のご準備は最小限。テーブルとスペースがあれば、どこでも開催可能です。' },
      { key: 'aboutText3', label: 'サービス紹介 本文3', type: 'textarea', default: 'イベント主催者様も、一般のお客様も、お気軽にご相談ください。人数やご予算に合わせた最適なプランをご提案いたします。' },
      { key: 'scenesTitle', label: '利用シーン 見出し', type: 'text', default: 'こんなシーンで活躍しています' },
      { key: 'scenesLead', label: '利用シーン 説明', type: 'textarea', default: 'さまざまなイベントや場所でワークショップを開催しています' },
      { key: 'scene1Title', label: '利用シーン1 見出し', type: 'text', default: 'マルシェ・フェスティバル' },
      { key: 'scene1Desc', label: '利用シーン1 説明', type: 'textarea', default: '地域のマルシェやフェスティバルで、来場者が気軽に参加できるワークショップブースを設置します。' },
      { key: 'scene2Title', label: '利用シーン2 見出し', type: 'text', default: '企業イベント・福利厚生' },
      { key: 'scene2Desc', label: '利用シーン2 説明', type: 'textarea', default: '社内レクリエーションやチームビルディングに。社員の皆様のリフレッシュや交流の場として好評です。' },
      { key: 'scene3Title', label: '利用シーン3 見出し', type: 'text', default: '学校・教育施設' },
      { key: 'scene3Desc', label: '利用シーン3 説明', type: 'textarea', default: '小学校や児童館、PTA行事などで自然と触れ合う体験学習として。お子様の創造力を育みます。' },
      { key: 'scene4Title', label: '利用シーン4 見出し', type: 'text', default: '結婚式・パーティー' },
      { key: 'scene4Desc', label: '利用シーン4 説明', type: 'textarea', default: '結婚式の余興やパーティーのアクティビティとして。ゲストの思い出に残る特別な体験を演出します。' },
      { key: 'menusTitle', label: 'メニュー 見出し', type: 'text', default: '選べるワークショップメニュー' },
      { key: 'menusLead', label: 'メニュー 説明', type: 'textarea', default: '持ち運びしやすいサイズを中心にご用意しています' },
      ...[1, 2, 3].flatMap((number) => {
        const defaults = [
          ['ガラスキャニスターSS', '6cm × 11cm', '基本容器', '手のひらサイズの小さな苔の世界。短時間で完成するため、イベントでも気軽に楽しめます。', '/images/workshop/glass-canister-ss.JPG', '約90分'],
          ['ガラスボールS', '10cm × 8cm', '応相談', '丸いガラスの中に広がる小さな苔の森。体験の満足度が高く、人気のメニューです。', '/images/workshop/glass-ball-s.JPG', '約120分'],
          ['ポップジャー', '11cm × 6cm', '応相談', 'ころんと可愛い形の容器で、お子様にも人気。イベントの記念にぴったりです。', '/images/workshop/pop-jar.JPG', '約120分'],
        ][number - 1];
        return [
          { key: `menu${number}Name`, label: `メニュー${number} 名称`, type: 'text' as const, default: defaults[0] },
          { key: `menu${number}Dimensions`, label: `メニュー${number} サイズ`, type: 'text' as const, default: defaults[1] },
          { key: `menu${number}Price`, label: `メニュー${number} 価格`, type: 'text' as const, default: defaults[2] },
          { key: `menu${number}Desc`, label: `メニュー${number} 説明`, type: 'textarea' as const, default: defaults[3] },
          { key: `menu${number}Image`, label: `メニュー${number} 画像`, type: 'image' as const, default: defaults[4] },
          { key: `menu${number}Time`, label: `メニュー${number} 所要時間`, type: 'text' as const, default: defaults[5] },
        ];
      }),
      { key: 'menusNote', label: 'メニュー 補足', type: 'textarea', default: '※ 出張ワークショップの基本材料費は1名あたり1,500円です。\n※ 上記以外のメニューもご相談に応じて対応可能です。\n※ 容器・内容の変更により追加費用が発生する場合があります。' },
      { key: 'pricingTitle', label: '料金・開催条件 見出し', type: 'text', default: '料金・開催条件' },
      { key: 'pricingLead', label: '料金・開催条件 説明', type: 'textarea', default: '出張ワークショップの基本料金と人数ごとの目安です' },
      { key: 'basicPricingTitle', label: '基本料金 見出し', type: 'text', default: '基本料金' },
      { key: 'assistanceTitle', label: '運営補助費 見出し', type: 'text', default: '運営補助費' },
      ...['講師料|30,000円／日', '材料費|1名あたり 1,500円', '交通費|実費', '基本容器サイズ|縦11cm × 横6cm'].flatMap((item, index) => {
        const [label, value] = item.split('|');
        return [
          { key: `price${index + 1}Label`, label: `基本料金${index + 1} 項目`, type: 'text' as const, default: label },
          { key: `price${index + 1}Value`, label: `基本料金${index + 1} 金額・内容`, type: 'text' as const, default: value },
        ];
      }),
      ...['〜20名|加算なし', '21〜30名|+10,000円', '31〜40名|+20,000円', '41〜50名|+30,000円'].flatMap((item, index) => {
        const [people, fee] = item.split('|');
        return [
          { key: `assist${index + 1}People`, label: `運営補助費${index + 1} 人数`, type: 'text' as const, default: people },
          { key: `assist${index + 1}Fee`, label: `運営補助費${index + 1} 加算額`, type: 'text' as const, default: fee },
        ];
      }),
      { key: 'figureLead', label: 'フィギュア 説明', type: 'textarea', default: '作品の完成度や制作の楽しさを考慮し、フィギュア付きでの開催を基本としております。' },
      { key: 'figureTitle', label: 'フィギュア 見出し', type: 'text', default: 'フィギュアについて' },
      { key: 'figure1Name', label: 'フィギュアプラン1 名称', type: 'text', default: '通常プラン' },
      { key: 'figure1Price', label: 'フィギュアプラン1 料金', type: 'text', default: 'フィギュア代 200〜500円（税込）／個' },
      { key: 'figure1Notes', label: 'フィギュアプラン1 詳細（1行1項目）', type: 'textarea', default: '希望者のみお選びいただけます\n種類によって価格が異なります\n使用数に応じて追加精算となります' },
      { key: 'figure2Name', label: 'フィギュアプラン2 名称', type: 'text', default: '法人・団体向け おまとめプラン' },
      { key: 'figure2Price', label: 'フィギュアプラン2 料金', type: 'text', default: '材料費 2,000円（税込）／名（フィギュア代込み）' },
      { key: 'figure2Notes', label: 'フィギュアプラン2 詳細（1行1項目）', type: 'textarea', default: '会計を簡略化したい場合におすすめです\n対象フィギュアから自由に選択可能\n追加精算不要でスムーズにご精算いただけます' },
      { key: 'hostingConditions', label: '開催条件（1行1項目）', type: 'textarea', default: '最小開催人数の定めはございません。講師料・材料費・交通費をお支払いいただければ開催いたします。\n1回あたり最大10名までを目安とし、1日最大2回まで開催可能です（原則20名まで）。\n20名以上での開催は、内容・運営体制を相談の上決定します。\n開催可能な最大人数は50名までです。51名以上での開催は承っておりません。\n少人数プランもございます。詳細はお問い合わせください。\nご相談時のスタッフ人数に応じて、開催可能な人数が変動する場合がございます。' },
      { key: 'hostingTitle', label: '開催条件 見出し', type: 'text', default: '開催条件' },
      { key: 'cancellationTitle', label: 'キャンセル料 見出し', type: 'text', default: 'キャンセル料' },
      ...['開催日の14日前以降|料金の30%', '開催日の7日前以降|料金の50%', '前日〜当日|料金の100%'].flatMap((item, index) => {
        const [timing, fee] = item.split('|');
        return [
          { key: `cancel${index + 1}Timing`, label: `キャンセル料${index + 1} 時期`, type: 'text' as const, default: timing },
          { key: `cancel${index + 1}Fee`, label: `キャンセル料${index + 1} 割合`, type: 'text' as const, default: fee },
        ];
      }),
      { key: 'cancellationNote', label: 'キャンセル料 補足', type: 'textarea', default: 'キャンセル料は、講師料・材料費・運営補助費・交通費等を含む総額を基準として算出いたします。\n資材準備・人員確保等のため、上記の規定とさせていただいております。' },
      { key: 'facilityGuides', label: '所要時間・設備目安（1行1項目）', type: 'textarea', default: '制作の所要時間は60〜120分です。容器・人数・内容により前後します。\n準備は約60分、撤収は約60分を目安としています。\n会議テーブル（180cm）1台につき、余裕を持って2名までを目安としています。\n対象年齢は小学生以上です。小学生は保護者同伴で参加可能です。' },
      { key: 'facilityTitle', label: '所要時間・設備目安 見出し', type: 'text', default: '所要時間・設備目安' },
      { key: 'importantNotes', label: '補足事項・注意事項（1行1項目）', type: 'textarea', default: 'ワークショップ中の怪我、衣服の汚れ等につきましては、一切責任を負いかねますのでご了承ください。\n制作後の管理環境や経年変化により、植物の状態が変化する場合がございます。\n記録・広報を目的として、制作風景を撮影させていただく場合がございます。\n天候不良、災害、交通機関の影響等により開催が困難な場合、日程変更または中止をご相談させていただく場合がございます。\nお支払いは開催日前までの事前精算をお願いしております。内容追加や人数変更等により発生した追加費用は後日精算をお願いいたします（請求書払いもご相談可能です）。' },
      { key: 'importantTitle', label: '補足事項・注意事項 見出し', type: 'text', default: '補足事項・注意事項' },
      { key: 'importantFooter', label: '補足事項・注意事項 末尾文', type: 'textarea', default: '上記内容は目安です。会場条件・安全配慮・スタッフ状況により調整する場合がございます。' },
      { key: 'featuresTitle', label: '特徴セクション 見出し', type: 'text', default: '出張ワークショップの特徴' },
      ...[1, 2, 3, 4].flatMap((number) => {
        const defaults = [
          ['準備はすべてお任せ', '材料・道具・テーブルクロスなど必要なものはすべて持参します。会場のご準備は最小限でOKです。'],
          ['経験豊富な職人が出向', '店舗と同じクオリティの指導を、あなたの会場で。丁寧なサポートで初めての方も安心です。'],
          ['人数・内容を柔軟に対応', '少人数のプライベートイベントから大人数のフェスまで。ご要望に合わせたプランをご提案します。'],
          ['完成作品はお持ち帰り', '作った作品はその場でお持ち帰りいただけます。イベントの素敵な記念品になります。'],
        ][number - 1];
        return [
          { key: `feature${number}Title`, label: `特徴${number} 見出し`, type: 'text' as const, default: defaults[0] },
          { key: `feature${number}Desc`, label: `特徴${number} 説明`, type: 'textarea' as const, default: defaults[1] },
        ];
      }),
      ...[1, 2, 3, 4].flatMap((number) => {
        const defaults = [
          ['お問い合わせ', 'お電話・メール・フォームからお気軽にご連絡ください'],
          ['お打ち合わせ', '日程・人数・会場・ご予算などをヒアリングします'],
          ['お見積り・準備', '最適なプランをご提案。材料の準備を進めます'],
          ['当日開催', '会場にお伺いし、楽しいワークショップを開催！'],
        ][number - 1];
        return [
          { key: `step${number}Title`, label: `ご依頼の流れ${number} 見出し`, type: 'text' as const, default: defaults[0] },
          { key: `step${number}Desc`, label: `ご依頼の流れ${number} 説明`, type: 'textarea' as const, default: defaults[1] },
        ];
      }),
      { key: 'stepsTitle', label: 'ご依頼の流れ 見出し', type: 'text', default: 'ご依頼の流れ' },
      { key: 'ctaTitle', label: 'お問い合わせ 見出し', type: 'text', default: '出張ワークショップのご相談、お気軽にどうぞ' },
      { key: 'ctaLead1', label: 'お問い合わせ 説明1', type: 'textarea', default: 'イベント主催者の方も、個人でのお問い合わせも大歓迎です。' },
      { key: 'ctaLead2', label: 'お問い合わせ 説明2', type: 'textarea', default: '「こんなイベントでできる？」「予算はどれくらい？」など、まずはお気軽にご連絡ください。' },
      { key: 'ctaNote', label: 'お問い合わせ 補足', type: 'textarea', default: '※ 出張範囲・交通費等についてはお問い合わせ時にご相談ください' },
    ],
  },
  workshop: {
    title: 'ワークショップページ',
    path: '/workshop',
    fields: [
      { key: 'heroTitle', label: 'ヒーロー見出し', type: 'text', default: '自分の手で作る、特別なテラリウム体験' },
      { key: 'heroLead', label: 'ヒーロー リード文', type: 'textarea', default: '経験豊富な職人が丁寧に指導する、本格的なテラリウム制作体験。親御さんにもお手伝いいただくことで小さなお子様も参加可能です。' },
      { key: 'plan1Name', label: 'プラン1 名称', type: 'text', default: 'ガラスキャニスターSS' },
      { key: 'plan1Price', label: 'プラン1 価格', type: 'text', default: '¥2,500' },
      { key: 'plan1Duration', label: 'プラン1 所要時間', type: 'text', default: '約90分' },
      { key: 'plan1Desc', label: 'プラン1 説明', type: 'textarea', default: '手のひらサイズの小さな苔の世界。初めての方にも気軽に楽しめる癒しの一本です。' },
      { key: 'plan1Image', label: 'プラン1 画像', type: 'image', default: '/images/workshop/glass-canister-ss.JPG' },
      { key: 'plan2Name', label: 'プラン2 名称', type: 'text', default: 'ガラスボールS' },
      { key: 'plan2Price', label: 'プラン2 価格', type: 'text', default: '¥4,000' },
      { key: 'plan2Duration', label: 'プラン2 所要時間', type: 'text', default: '約120分' },
      { key: 'plan2Desc', label: 'プラン2 説明', type: 'textarea', default: '丸いガラスの中に広がる小さな苔の森。日常に緑を添える、柔らかな印象のテラリウムです。' },
      { key: 'plan2Image', label: 'プラン2 画像', type: 'image', default: '/images/workshop/glass-ball-s.JPG' },
      { key: 'plan3Name', label: 'プラン3 名称', type: 'text', default: 'ポップジャー' },
      { key: 'plan3Price', label: 'プラン3 価格', type: 'text', default: '¥5,000' },
      { key: 'plan3Duration', label: 'プラン3 所要時間', type: 'text', default: '約120分' },
      { key: 'plan3Desc', label: 'プラン3 説明', type: 'textarea', default: 'ころんと可愛い形の容器に、立体的な苔の世界。インテリアにも映える明るい雰囲気です。' },
      { key: 'plan3Image', label: 'プラン3 画像', type: 'image', default: '/images/workshop/pop-jar.JPG' },
      { key: 'plan4Name', label: 'プラン4 名称', type: 'text', default: 'ガラスボールM' },
      { key: 'plan4Price', label: 'プラン4 価格', type: 'text', default: '¥8,500' },
      { key: 'plan4Duration', label: 'プラン4 所要時間', type: 'text', default: '' },
      { key: 'plan4Desc', label: 'プラン4 説明', type: 'textarea', default: '【所要時間：120~180分】存在感あるサイズに豊かな景色を凝縮。苔の奥行きや地形の変化をじっくり楽しめます。' },
      { key: 'plan4Image', label: 'プラン4 画像', type: 'image', default: '/images/workshop/glass-ball-m.JPG' },
      { key: 'plan5Name', label: 'プラン5 名称', type: 'text', default: 'ガラスボール・ボックスLL' },
      { key: 'plan5Price', label: 'プラン5 価格', type: 'text', default: '¥25,000' },
      { key: 'plan5Duration', label: 'プラン5 所要時間', type: 'text', default: '' },
      { key: 'plan5Desc', label: 'プラン5 説明', type: 'textarea', default: '※他ワークショップ参加経験者限定。\n※【2週間前予約必須】1~2日間で完成' },
      { key: 'plan5Image', label: 'プラン5 画像', type: 'image', default: '/images/workshop/glass-ball-box-ll.JPG' },
      { key: 'plan6Name', label: 'プラン6 名称', type: 'text', default: '崖景のテラリウム' },
      { key: 'plan6Price', label: 'プラン6 価格', type: 'text', default: '¥6,000' },
      { key: 'plan6Duration', label: 'プラン6 所要時間', type: 'text', default: '' },
      { key: 'plan6Desc', label: 'プラン6 説明', type: 'textarea', default: '岩肌と苔が織りなす、崖のような立体構造。小さな容器に自然の迫力と静けさを閉じ込めました。' },
      { key: 'plan6Image', label: 'プラン6 画像', type: 'image', default: '/images/products/moss-country_products_bottle.png' },
      { key: 'testimonial1Name', label: '感想1 お名前', type: 'text', default: '田中 美咲さん' },
      { key: 'testimonial1Age', label: '感想1 属性', type: 'text', default: '20代女性' },
      { key: 'testimonial1Course', label: '感想1 コース', type: 'text', default: 'レギュラーサイズ' },
      { key: 'testimonial1Comment', label: '感想1 コメント', type: 'textarea', default: '初めてのテラリウム作りでしたが、職人さんが丁寧に教えてくださって、とても楽しい2時間でした。作った作品は今も大切に育てています。' },
      { key: 'testimonial2Name', label: '感想2 お名前', type: 'text', default: '佐藤 恵子さん・太郎くん' },
      { key: 'testimonial2Age', label: '感想2 属性', type: 'text', default: '親子参加（太郎くん10歳）' },
      { key: 'testimonial2Course', label: '感想2 コース', type: 'text', default: 'コンパクトサイズ' },
      { key: 'testimonial2Comment', label: '感想2 コメント', type: 'textarea', default: '10歳の息子と参加しました。子供でも分かりやすい説明で、親子で楽しく制作できました。息子は自分で作ったテラリウムをとても大切にしています。' },
      { key: 'testimonial3Name', label: '感想3 お名前', type: 'text', default: '山田 健太さん' },
      { key: 'testimonial3Age', label: '感想3 属性', type: 'text', default: '30代男性' },
      { key: 'testimonial3Course', label: '感想3 コース', type: 'text', default: 'レギュラーサイズ' },
      { key: 'testimonial3Comment', label: '感想3 コメント', type: 'textarea', default: '職人さんの技術を間近で見ることができて、とても勉強になりました。苔の選び方や配置のコツなど、プロの技術を学べる貴重な体験でした。' },
      { key: 'step1Title', label: '予約の流れ1 タイトル', type: 'text', default: 'コース選択' },
      { key: 'step1Desc', label: '予約の流れ1 説明', type: 'text', default: 'あなたに合ったコースを選んでください' },
      { key: 'step2Title', label: '予約の流れ2 タイトル', type: 'text', default: '日程確認' },
      { key: 'step2Desc', label: '予約の流れ2 説明', type: 'text', default: 'ご希望の日時をお選びください' },
      { key: 'step3Title', label: '予約の流れ3 タイトル', type: 'text', default: 'お申し込み' },
      { key: 'step3Desc', label: '予約の流れ3 説明', type: 'text', default: 'お問い合わせフォームからお申し込み' },
      { key: 'step4Title', label: '予約の流れ4 タイトル', type: 'text', default: '当日参加' },
      { key: 'step4Desc', label: '予約の流れ4 説明', type: 'text', default: '楽しいテラリウム作りを体験！' },
      { key: 'mobileBannerTitle', label: '出張ワークショップ 見出し', type: 'text', default: '出張ワークショップ' },
      { key: 'mobileBannerLead', label: '出張ワークショップ 説明', type: 'textarea', default: 'イベントや会場にお伺いして、ワークショップを開催します。マルシェ、企業イベント、学校行事など、さまざまなシーンでご利用いただけます。' },
      { key: 'mobileBannerImage', label: '出張ワークショップ 画像', type: 'image', default: '/images/workshop/mosscountry_workshop.png' },
      { key: 'ctaTitle', label: 'CTAセクション 見出し', type: 'text', default: '今すぐワークショップに参加しませんか？' },
      { key: 'ctaLead', label: 'CTAセクション リード文', type: 'textarea', default: '職人の技術を間近で学びながら、世界に一つだけのテラリウムを作りましょう。親御さんにもお手伝いいただくことで、小さなお子様も参加可能です。' },
    ],
  },
};

export type PageId = keyof typeof pageContentRegistry;

export const PAGE_IDS = Object.keys(pageContentRegistry);

/** ページの全フィールドのデフォルト値を Record<key, default> で返す */
export function registryDefaults(pageId: string): Record<string, string> {
  const page = pageContentRegistry[pageId];
  if (!page) return {};
  return Object.fromEntries(page.fields.map(f => [f.key, f.default]));
}
